import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [toggle, setToggle] = useState(false);

  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='primary-header'>
        <div className='container'>
          <div className='nav-wrapper'>
            <Link href='/'>
              <img src='logo.svg' alt='logo' />
            </Link>
            <button
              onClick={() => setToggle((current) => !current)}
              aria-controls='primary-navigation'
              className='mobile-nav-toggle'
              aria-expanded={toggle}
            >
              <img
                className='icon-hamburger'
                src={`${toggle ? 'icon-close.svg' : 'icon-hamburger.svg'}`}
                alt=''
                aria-hidden='true'
              />
              <span className='visually-hidden'>Menu</span>
            </button>
            <nav
              className={`${toggle ? 'opened' : ''} primary-navigation `}
              id='primary-navigation'
            >
              <ul aria-label='Primary' role='list' className='nav-list'>
                <li>
                  <Link href='/'>Pricing</Link>
                </li>
                <li>
                  <Link href='/'>Product</Link>
                </li>
                <li>
                  <Link href='/'>About Us</Link>
                </li>
                <li>
                  <Link href='/'>Careers</Link>
                </li>
                <li>
                  <Link href='/'>Community</Link>
                </li>
              </ul>
            </nav>
            <button className='button display-md-inline-flex display-sm-none'>Get Started</button>
          </div>
        </div>
      </header>
      <main>
        <section className='padding-block-900'>
          <div className='even-columns'>
            <div>
              <h1 className='fs-primary-heading fw-bold'>
                Bring everyone together to build better products.
              </h1>
              <p>
                Manage makes it simple for software teams to plan day-to-day tasks while keeping the
                larger team goals in view.
              </p>
              <button className='button'>Get Started</button>
            </div>
            <div>
              <img src='illustration-intro.svg' alt='' />
            </div>
          </div>
        </section>
        <section className='container padding-block-900'>
          <div className='even-columns'>
            <div>
              <h2 className='fs-secondary-heading fw-bold'>What&apos;s different about Manage?</h2>
              <p>
                Manage provides all the functionality your team needs, without the complexity. Our
                software is tailor-made for modern digital product teams.
              </p>
            </div>
            <div>
              <ul className='numbered-items' role='list'>
                <li>
                  <h3 className='fs-600 fw-bold'>Track company-wide progress</h3>
                  <p>
                    See how your day-to-day tasks fit into the wider vision. Go from tracking
                    progress at the milestone level all the way done to the smallest of details.
                    Never lose sight of the bigger picture again.{' '}
                  </p>
                </li>
                <li>
                  <h3 className='fs-600 fw-bold'>Advanced built-in reports</h3>
                  <p>
                    Set internal delivery estimates and track progress toward company goals. Our
                    customisable dashboard helps you build out the reports you need to keep key
                    stakeholders informed.
                  </p>
                </li>
                <li>
                  <h3 className='fs-600 fw-bold'>Everything you need in one place</h3>
                  <p>
                    Stop jumping from one service to another to communicate, store files, track
                    tasks and share documents. Manage offers an all-in-one team productivity
                    solution
                  </p>
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section className='carousel padding-block-700'>
          <h2 className='fs-secondary-heading fw-bold'>What they said</h2>
          <button className='button'>Get Started</button>
        </section>
        <section className='cta | bg-accent-400 text-neutral-100 padding-block-700'>
          <div className='container'>
            <div className='even-columns'>
              <div>
                <p className='fs-secondary-heading fw-bold'>Simplify how your team works today.</p>
              </div>
              <div>
                <button className='button' data-type='inverted'>
                  Get Started
                </button>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className='padding-block-700 bg-neutral-900 text-neutral-100'>
        <div className='container'>
          <div className='even-columns'>
            <div>
              <ul role='list' aria-label='social links'>
                <li>
                  <Link aria-label='facebook' href='/'>
                    a
                  </Link>
                </li>
                <li>
                  <Link aria-label='youtube' href='/'>
                    b
                  </Link>
                </li>
                <li>
                  <Link aria-label='twitter' href='/'>
                    c
                  </Link>
                </li>
                <li>
                  <Link aria-label='pinterest' href='/'>
                    d
                  </Link>
                </li>
                <li>
                  <Link aria-label='instagram' href='/'>
                    e
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <nav className='footer-nav'>
                <ul aria-label='Footer' role='list'>
                  <li>
                    <Link href='/'>Home</Link>
                  </li>
                  <li>
                    <Link href='/'>Pricing</Link>
                  </li>
                  <li>
                    <Link href='/'>Products</Link>
                  </li>
                  <li>
                    <Link href='/'>About Us</Link>
                  </li>
                  <li>
                    <Link href='/'>Careers</Link>
                  </li>
                  <li>
                    <Link href='/'>Community</Link>
                  </li>
                  <li>
                    <Link href='/'>Privacy Policy</Link>
                  </li>
                </ul>
              </nav>
            </div>
            <div>
              <form action=''>
                <input type='email' />
                <button className='button'>Go</button>
                <p> Copyright 2020. All Rights Reserved</p>
              </form>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
